In [1]:
# source :
# https://www.w3schools.com/python/numpy/numpy_array_join.asp

In [2]:
import numpy as np

In [3]:
b=np.array(1) #0D array

In [4]:
print('the number of dimensions is {} and the shape is {}'.format(b.ndim,b.shape))

the number of dimensions is 0 and the shape is ()


In [5]:
a = np.array([1, 2, 3, 4]) #1-D array

In [6]:
a 

array([1, 2, 3, 4])

In [7]:
type(a)

numpy.ndarray

In [8]:
print('the 1st element is {}, the 2nd is {} and the last is {}'.format(a[0],a[1],a[3]))

the 1st element is 1, the 2nd is 2 and the last is 4


In [9]:
print('the number of dimensions is {} and the shape is {}'.format(a.ndim,a.shape))

the number of dimensions is 1 and the shape is (4,)


In [10]:
print(a)
print(a[0:-1])
print(a[0:3])
print(a[0:4])
print(a[0:4:1])
print(a[0:4:2])
print(a[:])
print(a[::])
print(a[::])
print(a[0:])
print(a[0::])
print(a[:4])
print(a[1:4])
print(a[1:4:1])

[1 2 3 4]
[1 2 3]
[1 2 3]
[1 2 3 4]
[1 2 3 4]
[1 3]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[2 3 4]
[2 3 4]


In [11]:
a_1 = np.expand_dims(a, 0)
a_2 = np.expand_dims(a, 1)
a_3 = np.expand_dims(a, -1)


In [12]:
print(a_1)
print(a_1.ndim, a_1.shape)

[[1 2 3 4]]
2 (1, 4)


In [13]:
print(a_2)
print(a_2.ndim, a_2.shape)

[[1]
 [2]
 [3]
 [4]]
2 (4, 1)


In [14]:
print(a_3)
print(a_3.ndim, a_3.shape)

[[1]
 [2]
 [3]
 [4]]
2 (4, 1)


In [15]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b[0,1]

2

In [17]:
print('the number of dimensions is {} and the shape is {}'.format(b.ndim,b.shape))

the number of dimensions is 2 and the shape is (2, 3)


In [18]:
b_1 = np.expand_dims(b, 0)
b_2 = np.expand_dims(b, 1)
b_3 = np.expand_dims(b, 2)
b_4 = np.expand_dims(b, -1)

In [19]:
print(b_1)
print(b_1.ndim, b_1.shape)

[[[1 2 3]
  [4 5 6]]]
3 (1, 2, 3)


In [20]:
print(b_2)
print(b_2.ndim, b_2.shape)

[[[1 2 3]]

 [[4 5 6]]]
3 (2, 1, 3)


In [21]:
print(b_3)
print(b_3.ndim, b_3.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
3 (2, 3, 1)


In [22]:
print(b_4)
print(b_4.ndim, b_4.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
3 (2, 3, 1)


In [23]:
m = np.arange(3, 15, 2)
m

array([ 3,  5,  7,  9, 11, 13])

In [24]:
n = range(3, 15, 2)
n

range(3, 15, 2)

In [25]:
np.arange(0, 11*np.pi, np.pi)

array([ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061,
       15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388,
       31.41592654])

In [26]:
range(0, 11*np.pi, np.pi)

TypeError: 'float' object cannot be interpreted as an integer

In [27]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [28]:
y = np.sin(np.pi)
y

1.2246467991473532e-16

In [29]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0:2,0:3])
print(arr[0:1,0:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [6 7 8]]
[[1 2 3 4]]


In [30]:
arr = np.array(['apple', 'banana', 'cherry'])
arr

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [31]:
arr = np.array([1, 2, 3, 4], dtype='S')
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [32]:
arr = np.array([1, 2, 3, 4], dtype='i4')
arr

array([1, 2, 3, 4], dtype=int32)

In [33]:
#converting data

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)
newarr

array([ True, False,  True])

In [34]:
arr = np.array([1, 2, 3, 4, 5]) #view IS affected by changes made to the original array.
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [35]:
arr = np.array([1, 2, 3, 4, 5]) #copy IS NOT affected by changes made to the original array.
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [36]:
arr = np.array([1, 2, 3, 4, 5]) #The original array IS affected by changes made to the view.
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [37]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) # return the original array of the object
print(y.base)

None
[1 2 3 4 5]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
#iterate an array

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [42]:
#concatenation of 2 arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([3, 5, 6])

arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 3, 5, 6])

In [43]:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
#concatenation of 2 arrays along colums
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
#concatenation of 2 arrays along rows
arr1 = np.concatenate((arr1, arr2), axis=1)
print(arr1)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [44]:
#stack : concatenation of 2 arrays along new axis

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)


[[1 4]
 [2 5]
 [3 6]]


In [45]:
# horizontal stack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [46]:
# vertical stack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [47]:
#split an array and return an array contaning n arrays
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [48]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
#returns the indexes of elements 4
x = np.where(arr == 4)
x

(array([3, 5, 6]),)

In [49]:
arr = np.array([6, 7, 8, 9])
#return the index in which we can insert the value in the sorted order from  right side
x = np.searchsorted(arr, 7,side='right')

print(x)

2


In [50]:
#sort array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [51]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [52]:

#unique values of array
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [55]:
from numpy import random
#the purpose is to get an  array of 100 elements of the 1st list with the probability from 2nd list (0,6 for 7 and 0.1 for 3 ...)
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 5 7 7 7 7 5 5 7 3 7 5 7 7 7 3 7 7 7 7 7 7 7 7 7 3 7 7 5 7 3 5 5 5 5
 5 7 3 7 3 5 5 7 3 7 5 5 7 3 7 7 5 7 7 5 7 7 7 5 7 7 7 7 7 7 7 7 7 3 7 5 5
 7 7 5 5 7 5 5 5 7 7 5 3 7 7 5 7 7 3 5 7 5 5 7 7 7 7]


In [58]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[4 3 2 5 1]


In [59]:
from numpy import random

x = random.normal(size=(2, 3))

print(x)

[[-0.51603778  0.35546589 -0.8219768 ]
 [ 0.42980854  0.55199612 -1.7840159 ]]


In [60]:
from numpy import random

x = random.logistic(loc=1, scale=2, size=(2, 3))

print(x)

[[ 1.63924004  5.56888562  4.80321882]
 [-3.99835361 -2.5078311   1.31618174]]
